# Generated by Django 4.0.4 on 2022-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolate',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chocolate',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\aziz\\media\\images'),
        ),
    ]
