# Generated by Django 4.0.4 on 2022-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_alter_chocolate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\aziz\\media\\images'),
        ),
    ]
